# /etc/updatedb.conf

# Ignore Binds
PRUNE_BIND_MOUNTS="yes"

# Filesystem types to exclude
PRUNEFS="nfs nfs4 proc sysfs tmpfs"

# Directory paths to exclude
PRUNEPATHS="/audit /bin /boot /conf /data /dev /etc /opt /proc /run /sbin /srv /sys /usr /tmp /var/spool /mnt/nfs /mnt/spool/SABnzbd/Incomplete /mnt/spool/SABnzbd/.nzb"

# Directory names to exclude (basename only, applies everywhere)
PRUNENAMES=".git .hg .svn .bzr"