on:
  push:
  pull_request:
  workflow_dispatch:

name: "ShellCheck: Push Action"
permissions: {}

jobs:
  ShellCheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2034 -e SC2162
        with:
          scandir: './bash'
          check_together: 'yes'
          format: tty